version: "3.3"

services:
  postgres_db:
    image: postgres:12.12
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: Postgres

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./django_grpc:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres_db
    container_name: DjangoApp

volumes:
  postgres_data:
